export enum Genre {
  Todas = "Todas",
  Acción = "Acción",
  Aventura = "Aventura",
  Animación = "Animación",
  Bélica = "Bélica",
  Biografia = "biografia",
  Cienciaficción = "Ciencia%20ficción",
  Comedia = "Comedia",
  Crimen = "Crimen",
  Drama = "Drama",
  Documental = "Documental",
  Familia = "Familia",
  Fantasía = "Fantasía",
  Historia = "Historia",
  Música = "Música",
  Misterio = "Misterio",
  Película_de_TV = "Película de TV",
  Romance = "Romance",
  Suspense = "Suspense",
  Terror = "Terror",
  Western = "Western",
}
